services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api_service
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
      - mqtt
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
      
  redis:
    image: redis:7.2-alpine
    container_name: redis_service
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app_network
    volumes:
      - redis_data:/data
      
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    restart: always
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    networks:
      - app_network
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    
volumes:
  redis_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
    
networks:
  app_network:
    driver: bridge